### PR TITLE
Linux pslist plugin - Add tasks real and effective user and group identifiers

### PR DESCRIPTION
**Pull request by gcmoreira**
This PR addresses #1410 by adding the real and effective user and group identifiers (uid, gid, euid, egid). 

Additionally:
- It refactors `pslist.get_task_fields()` using a **dataclass**, reducing the function's interface and mitigating unbounded growth. These updates simplify future modifications and improve maintainability.
- The  `linux.psscan` plugin was refactored to take advantage of the `pslist.get_task_fields()` changes and, avoiding code duplication and also improving maintainability.
- **pstree** and **pidhashtable** plugins were also updated to use the TaskFields.
- Updated all the pslist dependent plugins to use the correct version specified in the requirements.

```shell
$ ./vol.py -r pretty \
    -f ./linux-sample-1.bin \
    linux.pslist
Volatility 3 Framework 2.13.0
  |     OFFSET (V) |  PID |  TID | PPID |            COMM |  UID |   GID | EUID |  EGID |                  CREATION TIME | File output
* | 0x88001f994740 |    1 |    1 |    0 |            init |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.016001 UTC |    Disabled
* | 0x88001f994040 |    2 |    2 |    0 |        kthreadd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.016001 UTC |    Disabled
* | 0x88001f9a2780 |    3 |    3 |    2 |     ksoftirqd/0 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.056003 UTC |    Disabled
* | 0x88001f9a67c0 |    5 |    5 |    2 |     kworker/u:0 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.056003 UTC |    Disabled
* | 0x88001f9a60c0 |    6 |    6 |    2 |     migration/0 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.056003 UTC |    Disabled
* | 0x88001f9ab800 |    7 |    7 |    2 |      watchdog/0 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.060003 UTC |    Disabled
* | 0x88001f9ab100 |    8 |    8 |    2 |          cpuset |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.060003 UTC |    Disabled
* | 0x88001f9af840 |    9 |    9 |    2 |         khelper |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.060003 UTC |    Disabled
* | 0x88001f9af140 |   10 |   10 |    2 |       kdevtmpfs |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.060003 UTC |    Disabled
* | 0x88001f9c1880 |   11 |   11 |    2 |           netns |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.060003 UTC |    Disabled
* | 0x88001f9c1180 |   12 |   12 |    2 |     sync_supers |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.064003 UTC |    Disabled
* | 0x88001fa438c0 |   13 |   13 |    2 |     bdi-default |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.064003 UTC |    Disabled
* | 0x88001fa431c0 |   14 |   14 |    2 |     kintegrityd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.064003 UTC |    Disabled
* | 0x88001fa56740 |   15 |   15 |    2 |         kblockd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.068004 UTC |    Disabled
* | 0x88001fa56040 |   16 |   16 |    2 |      khungtaskd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.657132 UTC |    Disabled
* | 0x88001b42c780 |   17 |   17 |    2 |         kswapd0 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.657350 UTC |    Disabled
* | 0x88001b42c080 |   18 |   18 |    2 |            ksmd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.657540 UTC |    Disabled
* | 0x88001b4357c0 |   19 |   19 |    2 |   fsnotify_mark |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.657682 UTC |    Disabled
* | 0x88001b4350c0 |   20 |   20 |    2 |          crypto |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.658279 UTC |    Disabled
* | 0x88001b764840 |   61 |   61 |    2 |         ata_sff |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.846691 UTC |    Disabled
* | 0x88001b62e180 |   67 |   67 |    2 |      mpt_poll_0 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.854086 UTC |    Disabled
* | 0x88001f479080 |  101 |  101 |    2 |           mpt/0 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.864361 UTC |    Disabled
* | 0x88001f479780 |  102 |  102 |    2 |           khubd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:33.866864 UTC |    Disabled
* | 0x88001f4f27c0 |  142 |  142 |    2 |       scsi_eh_0 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:34.421784 UTC |    Disabled
* | 0x88001b7718c0 |  144 |  144 |    2 |       scsi_eh_1 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:34.534559 UTC |    Disabled
* | 0x88001f500800 |  145 |  145 |    2 |       scsi_eh_2 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:34.539379 UTC |    Disabled
* | 0x88001f1377c0 |  146 |  146 |    2 |     kworker/u:1 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:34.539575 UTC |    Disabled
* | 0x88001f2d71c0 |  177 |  177 |    2 |     jbd2/sda1-8 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:34.871826 UTC |    Disabled
* | 0x88001f2d78c0 |  178 |  178 |    2 | ext4-dio-unwrit |    0 |     0 |    0 |     0 | 2014-06-24 10:22:34.871871 UTC |    Disabled
* | 0x88001f085880 |  322 |  322 |    1 |           udevd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:35.095193 UTC |    Disabled
* | 0x88001f085180 |  431 |  431 |    2 |        ttm_swap |    0 |     0 |    0 |     0 | 2014-06-24 10:22:35.384558 UTC |    Disabled
* | 0x88001c1be080 |  468 |  468 |  322 |           udevd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:35.487350 UTC |    Disabled
* | 0x88001c3347c0 |  469 |  469 |  322 |           udevd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:35.487607 UTC |    Disabled
* | 0x88001c246180 |  512 |  512 |    2 |       kpsmoused |    0 |     0 |    0 |     0 | 2014-06-24 10:22:35.823578 UTC |    Disabled
* | 0x88001c65f7c0 |  553 |  553 |    2 |            hci0 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:35.902176 UTC |    Disabled
* | 0x88001f665840 | 1752 | 1752 |    1 |         rpcbind |    0 |     0 |    0 |     0 | 2014-06-24 10:22:37.719847 UTC |    Disabled
* | 0x88001bf1d800 | 1784 | 1784 |    1 |       rpc.statd |  105 | 65534 |  105 | 65534 | 2014-06-24 10:22:37.771603 UTC |    Disabled
* | 0x88001f107780 | 1789 | 1789 |    2 |          rpciod |    0 |     0 |    0 |     0 | 2014-06-24 10:22:37.794902 UTC |    Disabled
* | 0x88001f6ed740 | 1791 | 1791 |    2 |          nfsiod |    0 |     0 |    0 |     0 | 2014-06-24 10:22:37.816004 UTC |    Disabled
* | 0x88001be1e1c0 | 1798 | 1798 |    1 |      rpc.idmapd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:37.838232 UTC |    Disabled
* | 0x88001f0d9040 | 2057 | 2057 |    1 |        rsyslogd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.391747 UTC |    Disabled
* | 0x88001d5ed080 | 2157 | 2157 |    1 |           acpid |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.517995 UTC |    Disabled
* | 0x88001be1e8c0 | 2178 | 2178 |    1 |     dbus-daemon |  101 |   105 |  101 |   105 | 2014-06-24 10:22:38.554893 UTC |    Disabled
* | 0x88001c278080 | 2254 | 2254 |    1 |         apache2 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.683805 UTC |    Disabled
* | 0x88001aca0080 | 2344 | 2344 |    1 |             atd |    0 |     0 |    1 |     1 | 2014-06-24 10:22:38.729819 UTC |    Disabled
* | 0x88001ac987c0 | 2363 | 2363 |    1 |  NetworkManager |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.761895 UTC |    Disabled
* | 0x88001c86a040 | 2388 | 2388 |    1 |    avahi-daemon |  106 |   114 |  106 |   114 | 2014-06-24 10:22:38.802027 UTC |    Disabled
* | 0x88001ac980c0 | 2390 | 2390 | 2388 |    avahi-daemon |  106 |   114 |  106 |   114 | 2014-06-24 10:22:38.804543 UTC |    Disabled
* | 0x88001aca5180 | 2393 | 2393 |    1 |         polkitd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.808455 UTC |    Disabled
* | 0x88001d5e5140 | 2403 | 2403 |    1 |   modem-manager |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.844473 UTC |    Disabled
* | 0x88001acc2100 | 2425 | 2425 |    1 |            gdm3 |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.881212 UTC |    Disabled
* | 0x88001c1721c0 | 2440 | 2440 | 2425 | gdm-simple-slav |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.919535 UTC |    Disabled
* | 0x88001c717800 | 2450 | 2450 | 2363 |        dhclient |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.944889 UTC |    Disabled
* | 0x88001c1728c0 | 2451 | 2451 |    1 |      bluetoothd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.950863 UTC |    Disabled
* | 0x88001c65f0c0 | 2459 | 2459 | 2440 |            Xorg |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.979053 UTC |    Disabled
* | 0x88001f53e140 | 2467 | 2467 |    2 |        krfcommd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:38.988349 UTC |    Disabled
* | 0x88001aca0780 | 2532 | 2532 |    1 |            cron |    0 |     0 |    0 |     0 | 2014-06-24 10:22:39.262774 UTC |    Disabled
* | 0x88001c171040 | 2573 | 2573 |    1 |          daemon |    0 |     0 |    0 |     0 | 2014-06-24 10:22:39.492605 UTC |    Disabled
* | 0x88001c0ce140 | 2575 | 2575 | 2573 |     mpt-statusd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:39.495048 UTC |    Disabled
* | 0x88001c171740 | 2645 | 2645 |    1 | accounts-daemon |    0 |     0 |    0 |     0 | 2014-06-24 10:22:39.640565 UTC |    Disabled
* | 0x88001ad518c0 | 2652 | 2652 |    1 | console-kit-dae |    0 |     0 |    0 |     0 | 2014-06-24 10:22:39.663571 UTC |    Disabled
* | 0x88001d06c100 | 2720 | 2720 |    1 |           inetd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:39.681172 UTC |    Disabled
* | 0x88001d064840 | 2798 | 2798 |    1 |            nmbd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:39.999106 UTC |    Disabled
* | 0x88001d26f180 | 2802 | 2802 |    1 |         upowerd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:40.012110 UTC |    Disabled
* | 0x88001ad0e100 | 2803 | 2803 |    1 |            smbd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:40.054231 UTC |    Disabled
* | 0x88001d317840 | 2813 | 2813 | 2803 |            smbd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:40.087987 UTC |    Disabled
* | 0x88001cbb31c0 | 2974 | 2974 |    1 |    rtkit-daemon |  112 |   118 |  112 |   118 | 2014-06-24 10:22:40.450414 UTC |    Disabled
* | 0x88001c51f0c0 | 3300 | 3300 |    1 |           exim4 |  104 |   111 |  104 |   111 | 2014-06-24 10:22:41.338865 UTC |    Disabled
* | 0x88001d375840 | 3373 | 3373 |    1 |            sshd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.588938 UTC |    Disabled
* | 0x88001ca36740 | 3415 | 3415 |    1 |        winbindd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.726380 UTC |    Disabled
* | 0x88001ca517c0 | 3419 | 3419 | 3415 |        winbindd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.738997 UTC |    Disabled
* | 0x88001bc0d140 | 3444 | 3444 |    1 |         dovecot |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.817347 UTC |    Disabled
* | 0x88001d375140 | 3468 | 3468 |    1 |       minissdpd |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.859800 UTC |    Disabled
* | 0x88001cbbb840 | 3476 | 3476 |    1 |           getty |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.875105 UTC |    Disabled
* | 0x88001cac67c0 | 3477 | 3477 |    1 |           getty |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.875188 UTC |    Disabled
* | 0x88001adb0080 | 3478 | 3478 |    1 |           getty |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.875248 UTC |    Disabled
* | 0x88001c417800 | 3479 | 3479 |    1 |           getty |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.875529 UTC |    Disabled
* | 0x88001cba2740 | 3480 | 3480 |    1 |           getty |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.875632 UTC |    Disabled
* | 0x88001adc87c0 | 3481 | 3481 |    1 |           getty |    0 |     0 |    0 |     0 | 2014-06-24 10:22:41.875831 UTC |    Disabled
* | 0x88001c1be780 | 3482 | 3482 | 3444 |           anvil |  107 |   115 |  107 |   115 | 2014-06-24 10:22:42.347660 UTC |    Disabled
* | 0x88001c184040 | 3483 | 3483 | 3444 |             log |    0 |     0 |    0 |     0 | 2014-06-24 10:22:42.347830 UTC |    Disabled
* | 0x88001c9901c0 | 3485 | 3485 | 3444 |          config |    0 |     0 |    0 |     0 | 2014-06-24 10:22:42.367918 UTC |    Disabled
* | 0x88001ca50780 | 3575 | 3575 | 2254 |         apache2 |   33 |    33 |   33 |    33 | 2014-06-24 10:27:39.343914 UTC |    Disabled
* | 0x88001f1370c0 | 3576 | 3576 | 2254 |         apache2 |   33 |    33 |   33 |    33 | 2014-06-24 10:27:39.344505 UTC |    Disabled
* | 0x88001f6ed040 | 3578 | 3578 | 2254 |         apache2 |   33 |    33 |   33 |    33 | 2014-06-24 10:27:39.344613 UTC |    Disabled
* | 0x88001d5e5840 | 3728 | 3728 |    2 |         kauditd |    0 |     0 |    0 |     0 | 2014-06-24 10:29:16.621401 UTC |    Disabled
* | 0x88001cac8780 | 3733 | 3733 | 2440 | gdm-session-wor |    0 |  1000 |    0 |  1000 | 2014-06-24 10:29:28.159554 UTC |    Disabled
* | 0x88001cbab880 | 3737 | 3737 |    1 | gnome-keyring-d | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:33.409351 UTC |    Disabled
* | 0x88001cb68040 | 3754 | 3754 | 3733 | x-session-manag | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:33.487818 UTC |    Disabled
* | 0x88001cb68740 | 3794 | 3794 | 3754 |       ssh-agent | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:33.677013 UTC |    Disabled
* | 0x88001c86a740 | 3797 | 3797 |    1 |     dbus-launch | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:33.678902 UTC |    Disabled
* | 0x88001cac41c0 | 3798 | 3798 |    1 |     dbus-daemon | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:33.681200 UTC |    Disabled
* | 0x88001caf71c0 | 3807 | 3807 | 3754 | gnome-settings- | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:33.816028 UTC |    Disabled
* | 0x88001cbed180 | 3818 | 3818 |    1 |           gvfsd | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:33.864551 UTC |    Disabled
* | 0x88001ad0e800 | 3824 | 3824 |    1 |      pulseaudio | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:33.951530 UTC |    Disabled
* | 0x88001c3340c0 | 3828 | 3828 |    1 | gvfs-gdu-volume | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.051188 UTC |    Disabled
* | 0x88001ad511c0 | 3830 | 3830 |    1 |   udisks-daemon |    0 |     0 |    0 |     0 | 2014-06-24 10:29:34.075154 UTC |    Disabled
* | 0x88001f0b01c0 | 3831 | 3831 | 3830 |   udisks-daemon |    0 |     0 |    0 |     0 | 2014-06-24 10:29:34.089851 UTC |    Disabled
* | 0x88001cb93800 | 3834 | 3834 |    1 | gvfs-gphoto2-vo | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.130516 UTC |    Disabled
* | 0x88001cbd6080 | 3836 | 3836 |    1 | gvfs-afc-volume | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.152077 UTC |    Disabled
* | 0x88001f737080 | 3841 | 3841 |    1 |          colord |  102 |   106 |  102 |   106 | 2014-06-24 10:29:34.180316 UTC |    Disabled
* | 0x88001f665140 | 3842 | 3842 | 3754 |        metacity | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.196481 UTC |    Disabled
* | 0x88001adc80c0 | 3852 | 3852 |    1 |     colord-sane |  102 |   106 |  102 |   106 | 2014-06-24 10:29:34.317672 UTC |    Disabled
* | 0x88001f667840 | 3854 | 3854 |    1 |     gsd-printer | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.332627 UTC |    Disabled
* | 0x88001d5ed780 | 3856 | 3856 | 3754 |     gnome-panel | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.345126 UTC |    Disabled
* | 0x88001d2ff800 | 3868 | 3868 |    1 |        gconfd-2 | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.561508 UTC |    Disabled
* | 0x88001d2ff100 | 3870 | 3870 |    1 |   dconf-service | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.629492 UTC |    Disabled
* | 0x88001f68a0c0 | 3874 | 3874 | 3754 |   tracker-store | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.676766 UTC |    Disabled
* | 0x88001bc1c180 | 3875 | 3875 | 3754 | notification-da | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.687322 UTC |    Disabled
* | 0x88001f0518c0 | 3876 | 3876 | 3754 | polkit-gnome-au | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.690588 UTC |    Disabled
* | 0x88001f0511c0 | 3877 | 3877 | 3754 | gnome-sound-app | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.697417 UTC |    Disabled
* | 0x88001f082740 | 3878 | 3878 | 3754 | gdu-notificatio | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.709200 UTC |    Disabled
* | 0x88001f082040 | 3879 | 3879 | 3754 | evolution-alarm | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.765386 UTC |    Disabled
* | 0x88001f0070c0 | 3883 | 3883 | 3754 | bluetooth-apple | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.808891 UTC |    Disabled
* | 0x88001d522800 | 3884 | 3884 | 3754 | gnome-screensav | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.830143 UTC |    Disabled
* | 0x88001ac9e8c0 | 3885 | 3885 | 3754 | gnome-fallback- | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.852555 UTC |    Disabled
* | 0x88001f654840 | 3887 | 3887 | 3754 |       nm-applet | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.884776 UTC |    Disabled
* | 0x88001cb93100 | 3889 | 3889 | 3754 | tracker-miner-f | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:34.967948 UTC |    Disabled
* | 0x88001af86080 | 3924 | 3924 |    1 | mission-control | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:36.015538 UTC |    Disabled
* | 0x880004404100 | 3929 | 3929 |    1 |      goa-daemon | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:29:36.068542 UTC |    Disabled
* | 0x88001afd67c0 | 3968 | 3968 | 3856 |  gnome-terminal | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:36:39.882135 UTC |    Disabled
* | 0x88001c581140 | 3975 | 3975 | 3968 | gnome-pty-helpe | 1000 |  1000 | 1000 |    43 | 2014-06-24 10:36:40.099195 UTC |    Disabled
* | 0x88001f68a7c0 | 3976 | 3976 | 3968 |            bash | 1000 |  1000 | 1000 |  1000 | 2014-06-24 10:36:40.116245 UTC |    Disabled
* | 0x88001f0b08c0 | 8099 | 8099 |    2 |       flush-8:0 |    0 |     0 |    0 |     0 | 2014-06-24 12:02:44.857271 UTC |    Disabled
* | 0x88001ae6d8c0 | 8105 | 8105 |    2 |     kworker/0:1 |    0 |     0 |    0 |     0 | 2014-06-24 12:10:16.003074 UTC |    Disabled
* | 0x88001f18e140 | 8471 | 8471 | 2575 |           sleep |    0 |     0 |    0 |     0 | 2014-06-24 12:52:39.968178 UTC |    Disabled
* | 0x88001b5e3140 | 8492 | 8492 |    2 |     kworker/0:2 |    0 |     0 |    0 |     0 | 2014-06-24 12:55:34.003716 UTC |    Disabled
* | 0x88001d06c800 | 8497 | 8497 | 3373 |            sshd |    0 |     0 |    0 |     0 | 2014-06-24 12:58:52.986083 UTC |    Disabled
* | 0x88001d3a7180 | 8502 | 8502 | 8497 |            sshd | 1001 |  1001 | 1001 |  1001 | 2014-06-24 12:58:55.472387 UTC |    Disabled
* | 0x88001ac9c740 | 8503 | 8503 | 8502 |            bash | 1001 |  1001 | 1001 |  1001 | 2014-06-24 12:58:55.474586 UTC |    Disabled
* | 0x88001f53e840 | 8599 | 8599 | 3976 |            sudo |    0 |  1000 |    0 |  1000 | 2014-06-24 13:00:21.592988 UTC |    Disabled
* | 0x8800044a5880 | 8600 | 8600 | 8599 |            bash |    0 |     0 |    0 |     0 | 2014-06-24 13:00:21.598157 UTC |    Disabled
* | 0x88001f9a2080 | 8601 | 8601 |    2 |     kworker/0:0 |    0 |     0 |    0 |     0 | 2014-06-24 13:00:36.003136 UTC |    Disabled
```

### CODE REVIEW

**Review by ikelos — APPROVED** [review]
This touches a lot of plugins, but looks thorough and passes our tests so...  5:)

**Comment by gcmoreira** [comment]
> This touches a lot of plugins, but looks thorough and passes our tests so... 5:)

I know, unfortunately, this issue arises every time we modify pslist due to its dependencies. I was considering addressing this by versioning `TaskFields`, so any new field would be an additive change, affecting only the features that require it. However, this would also introduce a new requirement for each plugin to support the updated version. thoughts?

**Comment by ikelos** [comment]
You'd essentially be swapping one version for another.  At least with TaskFields, you can now add new fields with only an additive (MINOR) bump.  Then depending plugins only need to know which version they need, but old plugins say working because the yielded value would still work.  That wouldn't require TaskFields to be versioned separately, just that the plugin version be bumped (additive) if any changes are made to TaskFields.

**Comment by ikelos** [comment]
We also need to add a testcase for running volshell.  The linux module in volshell has a plugin requirement on pslist (which I've now fixed), but a test case can easily help us avoid that.  Volshell doesn't terminate, but using a `--script` should let us check the exit value, which for an exception shouldn't be 0...

**Pull request merged**
