### PR TITLE
Linux: Sockstat - adds pytest

### PR DESCRIPTION
**Pull request by dgmcdona**
This adds a pytest for the `linux.sockstat.Sockstat` plugin.

### CODE REVIEW

**Comment by dgmcdona** [comment]
This is going to fail until  #1278 is merged - should I leave it as its own PR or add this to the other as an additional commit?

**Comment by ikelos** [comment]
Seems to break, but otherwise I'm in favour of more tests...

**Comment by dgmcdona** [comment]
> Seems to break, but otherwise I'm in favour of more tests...

It's fixed now that #1278 is merged

**Review by ikelos — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
