### PR TITLE
Documentation: update for `README`, `CODE_OF_CONDUCT`.

### PR DESCRIPTION
**Pull request by digitalisx**
Hello, everyone in the community. 🙂

Volatility 3 is already a famous project among many analysts.
Nevertheless, I hope this wonderful project gets more attention from more people and the community gets more active!

So I did some documentation work. ([Preview](https://github.com/digitalisx/volatility3/tree/feature/readme))
The details are as follows.

- Through badges, logos, and screenshots, visitors can see more visually what kind of project it is and what is active.
(The current logo is less visible in the dark theme, and if the foundation can provide a white image, I will take measures to make this change according to the theme.)

- Conversion of an existing text link to a hyperlink successfully. This allows us to focus more on reading sentences.

- Hyperlinks to some famous services have been made more intuitive with separate buttons.

- By adding images and numbers of contributors, we show how many and good members of the community are together.

- By adding a basic contribution guide to open source and a CoC, we added manners and attitudes that the community should have. (This follows the standard provided by Github by default, but it would be nice to have Volatile3's own contribution guide later on.)

In order to provide the most effective information and make a good README, I referred to many README in large projects. (Google, MS, etc.. )
 
However, the composition and content of the documentation can be subjective and will require opinion from the maintainers and members. Any opinion is fine.

### CODE REVIEW

**Comment by ikelos** [comment]
Thanks very much for this, adding a code-of-conduct just needs agreement by the whole of the core team, but I'll put it to them a the next meeting and we'll let you know if it's all good or if there's any tweaks we'd like.  5:)

**Comment by digitalisx** [comment]
Thank you @ikelos.
This PR is very important, the philosophy and direction of the core team. I will happily wait until it's decided! 🙌

**Comment by digitalisx** [comment]
Oh, very fortunately now [officially](https://github.com/github-community/community/discussions/16910
) in the Github darkmode logo for the conversion of support.We are in an environment of all users can create a better readme. 👏

But the images you want to use in dark mode is still no.
When I have time to patch this, myself produce an image or community will be offer. :)

**Comment by digitalisx** [comment]
Hello @awalters, I would appreciate it if you could leave your comments when you have time.

**Comment by digitalisx** [comment]
Is there any progress on this? Apart from `CoC`, the update of `README` could help a little more contributors and users.

**Comment by ikelos** [comment]
If you remove the CoC and submit it as a different pull request, this one can probably get merged pretty quickly.  Unfortunately derived a Code of Conduct for a project requires a fair amount of thought and consideration before adding...

**Comment by digitalisx** [comment]
As you said, the establishment of CoC is something that needs to be considered a lot.
Just I wondered the maintainer's think about this PR, Thank you for your answer @ikelos. :)

**Comment by digitalisx** [comment]
All right, this will be changed to a new PR in the near future. I close this PR to reorganize it! :)

**Pull request closed without merging**
