### PR TITLE
add linux envars

### PR DESCRIPTION
**Pull request by eve-mem**
This adds a linux equivalent of the envars plugin

### CODE REVIEW

**Review by ikelos — COMMENTED** [review]
This all looks good, proper style, didn't spot any errors or anything.  If @atcuno (who knows more about linux structures than I do) oks it then, it can go in, thanks!  5:D

**Comment by ikelos** [comment]
Looks like there's a little bit of linting which it would be nice if you could update?  We've just recently moved to using black for our formatting, so either using the patch in the output, or running black yourself over it and making the suggested changes would be good.  5:)

**Comment by eve-mem** [comment]
I will fix that linting issue. The code should look familiar to @atcuno, this is essentially the psaux plugin, but focusing on environment vars rather than the augments. An easy change for me to make.

**Comment by eve-mem** [comment]
I've fixed the linting issue now. I realized I never showed an example of the plugin output:

```
python vol.py -f linux-sample-4.dmp linux.envars
Volatility 3 Framework 2.4.1
Progress:  100.00               Stacking attempts finished
PID     PPID    COMM    KEY     VALUE

1       0       init    HOME    /
1       0       init    init    /sbin/init
1       0       init    TERM    linux
1       0       init    BOOT_IMAGE      /boot/vmlinuz-3.2.0-4-amd64
1       0       init    PATH    /sbin:/usr/sbin:/bin:/usr/bin
1       0       init    PWD     /
1       0       init    rootmnt /root
312     1       udevd   CONSOLE /dev/console
312     1       udevd   HOME    /
312     1       udevd   init    /sbin/init
312     1       udevd   runlevel        S
312     1       udevd   INIT_VERSION    sysvinit-2.88
312     1       udevd   TERM    linux
312     1       udevd   BOOT_IMAGE      /boot/vmlinuz-3.2.0-4-amd64
312     1       udevd   PATH    /sbin:/bin
312     1       udevd   RUNLEVEL        S
312     1       udevd   PREVLEVEL       N
312     1       udevd   SHELL   /bin/sh
312     1       udevd   PWD     /
312     1       udevd   previous        N
312     1       udevd   rootmnt /root
433     312     udevd   CONSOLE /dev/console
433     312     udevd   HOME    /
433     312     udevd   init    /sbin/init
433     312     udevd   runlevel        S
433     312     udevd   INIT_VERSION    sysvinit-2.88
433     312     udevd   TERM    linux
433     312     udevd   BOOT_IMAGE      /boot/vmlinuz-3.2.0-4-amd64
<snip>
```

filtered to a process:
```
python vol.py -f linux-sample-4.dmp linux.envars --pid 5572
Volatility 3 Framework 2.4.1
Progress:  100.00               Stacking attempts finished
PID     PPID    COMM    KEY     VALUE

5572    5571    bash    LANG    en_US.UTF-8
5572    5571    bash    USER    mark
5572    5571    bash    LOGNAME mark
5572    5571    bash    HOME    /home/mark
5572    5571    bash    PATH    /usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
5572    5571    bash    MAIL    /var/mail/mark
5572    5571    bash    SHELL   /bin/bash
5572    5571    bash    SSH_CLIENT      192.168.201.1 50377 22
5572    5571    bash    SSH_CONNECTION  192.168.201.1 50377 192.168.201.161 22
5572    5571    bash    SSH_TTY /dev/pts/0
5572    5571    bash    TERM    xterm-256color
5572    5571    bash    XDG_SESSION_COOKIE      7d727592b356a37133b61ce953a4a944-1403694186.321604-754756753
```

**Comment by eve-mem** [comment]
I've fixed the linting issue now. I realized I never showed an example of the plugin output:

```
python vol.py -f linux-sample-4.dmp linux.envars
Volatility 3 Framework 2.4.1
Progress:  100.00               Stacking attempts finished
PID     PPID    COMM    KEY     VALUE

1       0       init    HOME    /
1       0       init    init    /sbin/init
1       0       init    TERM    linux
1       0       init    BOOT_IMAGE      /boot/vmlinuz-3.2.0-4-amd64
1       0       init    PATH    /sbin:/usr/sbin:/bin:/usr/bin
1       0       init    PWD     /
1       0       init    rootmnt /root
312     1       udevd   CONSOLE /dev/console
312     1       udevd   HOME    /
312     1       udevd   init    /sbin/init
312     1       udevd   runlevel        S
312     1       udevd   INIT_VERSION    sysvinit-2.88
312     1       udevd   TERM    linux
312     1       udevd   BOOT_IMAGE      /boot/vmlinuz-3.2.0-4-amd64
312     1       udevd   PATH    /sbin:/bin
312     1       udevd   RUNLEVEL        S
312     1       udevd   PREVLEVEL       N
312     1       udevd   SHELL   /bin/sh
312     1       udevd   PWD     /
312     1       udevd   previous        N
312     1       udevd   rootmnt /root
433     312     udevd   CONSOLE /dev/console
433     312     udevd   HOME    /
433     312     udevd   init    /sbin/init
433     312     udevd   runlevel        S
433     312     udevd   INIT_VERSION    sysvinit-2.88
433     312     udevd   TERM    linux
433     312     udevd   BOOT_IMAGE      /boot/vmlinuz-3.2.0-4-amd64
<snip>
```

filtered to a process:
```
python vol.py -f linux-sample-4.dmp linux.envars --pid 5572
Volatility 3 Framework 2.4.1
Progress:  100.00               Stacking attempts finished
PID     PPID    COMM    KEY     VALUE

5572    5571    bash    LANG    en_US.UTF-8
5572    5571    bash    USER    mark
5572    5571    bash    LOGNAME mark
5572    5571    bash    HOME    /home/mark
5572    5571    bash    PATH    /usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
5572    5571    bash    MAIL    /var/mail/mark
5572    5571    bash    SHELL   /bin/bash
5572    5571    bash    SSH_CLIENT      192.168.201.1 50377 22
5572    5571    bash    SSH_CONNECTION  192.168.201.1 50377 192.168.201.161 22
5572    5571    bash    SSH_TTY /dev/pts/0
5572    5571    bash    TERM    xterm-256color
5572    5571    bash    XDG_SESSION_COOKIE      7d727592b356a37133b61ce953a4a944-1403694186.321604-754756753
```

**Comment by atcuno** [comment]
this looks ready for merge to me @ikelos

**Pull request merged**
