### PR TITLE
Fix: workflow `runs-on` version to `ubuntu-20.04`.

### PR DESCRIPTION
**Pull request by digitalisx**
## Description

This PR has come from this PR (#873).
We can use the minimum python version of bump to `3.7` through recently work.
I try to unify all of workflows because they use the `ubuntu-latest`.

### CODE REVIEW

**Comment by ikelos** [comment]
I wasn't sure if we were targetting an old ubuntu intentionally?  Happy to make the change if @npetroni is happy with it...

**Comment by npetroni** [comment]
> I wasn't sure if we were targetting an old ubuntu intentionally? Happy to make the change if @npetroni is happy with it...

I'm not sure if I care which specific Ubuntu version we use, but it does seem possible that a "lesson learned" from using `ubuntu-latest` should be that it can start breaking without warning. I think I'd prefer picking a named Ubuntu version. Moving to 22.04 seems reasonable but I'm also fine with keeping 20.04 since that will be supported for a couple more years and represents the "lagging edge" of our user base.

**Comment by digitalisx** [comment]
@npetroni Thank you for your opinion.
Then, would it be a little better to unify the version of ubuntu used in this project to `20.04`?

**Comment by ikelos** [comment]
Yes please, let's go with `ubuntu-20.04` for both then...

**Review by ikelos — APPROVED** [review]

**Comment by npetroni** [comment]
Thanks all! Sounds good.

**Pull request merged**
