### PR TITLE
task_struct get all threads from the parent task.

### PR DESCRIPTION
**Pull request by samuelzurowski**
Hello,

I found myself wanting to go through the thread_nodes of a given process often for Linux images. Thought other people who are developing plugins or other modules may find this useful when dealing with the task_struct. The picture bellow shows what this small function does.

image

### CODE REVIEW

**Comment by samuelzurowski** [comment]
I modified this to use the same concept for volatility2 using thread_group instead (see [volatility2 threads](https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/overlays/linux/linux.py#L1909)). Eventually going to use this to create a threads plugin for volatility3. 

Also added some comments so people can understand what it is doing.

**Comment by samuelzurowski** [comment]
I made a threads plugin too. Once this is sorted out ill send a PR for linux.threads I've worked on!

**Comment by ikelos** [comment]
Thanks, I'll just check this with our linux plugin chap (@atcuno) that he's happy with this addition.  Ideally there'd be a way to version this bit of code, so people knew that this method would be here or not.  It may just be we have to bump the volatility framework version, but since it's an additive change, we can just bump the minor version number.

**Comment by atcuno** [comment]
@ikelos This looks good to me, and I would like to get it merged ASAP so Gus' code in #600 can be adjusted to use it. In particular, the to_list approach covers smear with 'seen' and always does the try/except on referencing .next:

https://github.com/volatilityfoundation/volatility3/blob/581251cb0547b118ef01687aed81aab0a2f75f6d/volatility3/framework/symbols/linux/extensions/__init__.py#L434

Also, I see this code uses the "f" syntax but I believe our minimum Python version requirement covers this now right? I know we discussed this before, but I wanted to be extra careful.

**Comment by ikelos** [comment]
Yep, f-strings came in in version 3.6, which is now our minimum, so I think we've changed a lot of the code base to use them, should be all good now.  5:)

**Review by ikelos — APPROVED** [review]
Ok, I'll allow this one in without versioning, because it's an additive change, but as I say, at some point we should really consider versioning these and requiring specific versions through a requirement.

**Pull request merged**
