### PR TITLE
Add elf parsing and symbol retrieval for linux kernel modules

### PR DESCRIPTION
**Pull request by xabiugarte**

### CODE REVIEW

**Comment by xabiugarte** [comment]
Hi volatility developers,

I have added support for parsing ELFs in memory and retrieving their program headers, symbols, etc, following how it was implemented in Volatility2. I have not implemented all the functionalities present in Volatility2, only what I needed for PyREBox to work. In the future, if you are interested, I could add the missing functionality. I have decided to submit this pull request at this moment instead of making it larger.

**Comment by ikelos** [comment]
Hiya @xabiugarte, any progress on this?  There's outstanding comments to be addressed, we can address them, just need to know how you want to handle it...

**Comment by ikelos** [comment]
@xabiugarte I'm really keen to get this merged in, it's a great piece of work it just needs those few changes and comments addressing.  I realize everything's gone a little bit strange in the world at the moment, but do please let us know if there's any more information or questions/comments you may have about getting these updated?

**Comment by xabiugarte** [comment]
Hi @ikelos , sorry for the silence, I somehow missed your previous message. I will try to allocate some time to finally fix this pull request and submit it. I apologize for the long wait...

**Comment by ikelos** [comment]
Not a problem, just glad you're still happy contributing!  5:D

**Comment by ikelos** [comment]
@xabiugarte This is just a gentle prod, in case it slipped off your list.  We're still happy to help get this resolved and re-reviewed if you're still up for making the suggested changes?  Just let us know...  5:)

**Comment by xabiugarte** [comment]
Hi @ikelos,

Thanks for the reminder. I'll finish this next week and update the PR.

**Comment by ikelos** [comment]
@xabiugarte Any progress on this?  It's now holding up some other pull requests, so we may merge this and fix it up ourselves before the next meeting on Wednesday if they're not ready yet.  If you can get them in in the next couple of days then please push them through.  Hope that's ok?

**Comment by xabiugarte** [comment]
Hi @ikelos , I will submit the PR later today.

**Comment by xabiugarte** [comment]
Hi @ikelos 

I have addressed your comments. I've replaced setters by properties. Let me know if that's aligned with your coding practices  or if further changes are needed. 

Again, sorry for the long wait.

Xabi

**Comment by ikelos** [comment]
Ok, so I couldn't merge this through the github UI, but it has now been merged with proper attribution..  Thanks again!  5:)

**Pull request closed without merging**
