### PR TITLE
Added new containing address flag to vadinfo plugin

### PR DESCRIPTION
**Pull request by paulkermann**
Hey,
added new flag to `windows.vadinfo` plugin to also check the containing address in a certain VAD

### CODE REVIEW

**Comment by ikelos** [comment]
This feels as though the address filter isn't all that useful since it's highly specific.  Could both the address and containing-address be rolled into a single filter?  @iMHLv2 could you comment on this please?

**Comment by paulkermann** [comment]
You think I can make the --address flag also search addresses inside a given VAD?
I added a second flag to not change current API

**Comment by paulkermann** [comment]
I merged the two flags together, as you requested

**Review by ikelos — APPROVED** [review]
Looks good, thanks.  5:)

**Pull request merged**
