### PR TITLE
ability to reverse filtering see long description

### PR DESCRIPTION
**Pull request by doomedraven**
Hello, this is very useful to optimize some scans, like in case of sandboxing, imagine:
1 round it scans only all processes that was captured by sandbox aka pid_list
2. round it scans all the rest processes ignoring pid_list from round 1

if you have a better idea how to improve/implement this, let me know, we use our custom function, but i think it might be useful for the rest

### CODE REVIEW

**Review by ikelos — COMMENTED** [review]
Looks reasonable, but since it's technically an addition to the API, the third value of the version number for pslist plugin needs to be increased and any plugin that expects to be able to use exclude and then depend on it...

**Comment by doomedraven** [comment]
increased

**Comment by doomedraven** [comment]
do i need to fix any current plugin in vol to fix the version increase?

**Comment by ikelos** [comment]
Nope, as long as the only part of the (x, y, z) version number that was increased was the `z` then all existing plugins should work with it fine...

**Comment by doomedraven** [comment]
ah cool

**Review by ikelos — APPROVED** [review]

**Pull request merged**
