### PR TITLE
Tweak configuration.py

### PR DESCRIPTION
**Pull request by j-t-1**
Create a tuple directly and replace random.choice by random.choices.

### CODE REVIEW

**Comment by j-t-1** [comment]
Should line 784 have `float`?

**Review by ikelos — APPROVED** [review]
Looks good, thanks!

**Comment by j-t-1** [comment]
Should line 784 include a `float` as a simple type? Differs from line 49.

**Comment by ikelos** [comment]
`float`s weren't supposed to be part of the `BasicTypes` and I don't think they're used anywhere?  That should probably use the variable though...

**Pull request merged**
