### PR TITLE
Remove: Unused `pytest` module, duplicate `rc`.

### PR DESCRIPTION
**Pull request by digitalisx**
## Description
Hello, everyone in the community! 🙂
I found some unused or not essential code for while fix test script.

### CODE REVIEW

**Comment by digitalisx** [comment]
Hello, @fgomulka
If you time permits, I'd like to ask for a review to see if this PR is valid.
There was no problem with the test, but I wonder if there was any other intention.

**Review by ikelos — APPROVED** [review]
If pytest isn't used, this looks fine.  Happy to merge and then revert if necessary.

**Comment by fgomulka** [comment]
> Hello, @fgomulka If you time permits, I'd like to ask for a review to see if this PR is valid. There was no problem with the test, but I wonder if there was any other intention.

It looks great to me!

**Comment by digitalisx** [comment]
@fgomulka Thank you for taking the time to check! :)

**Pull request merged**
